### ISSUE TITLE
Provide vacuum entity autoconfiguration

### ISSUE THREAD

**Issue by davygravy** [davygravy/roomba-mqtt-homeassistant#2]
ATM, this setup configures 15 sensors, as can be seen in MQTT Explorer.
```
{
  "state": "idle",
  "fan_speed": "off",
  "battery_level": 85,
  "bump_left": false,
  "bump_right": false,
  "wheel_drop_left": false,
  "wheel_drop_right": false,
  "dirt_level": 0,
  "voltage": 15669,
  "battery_charge": 2298,
  "battery_capacity": 2696,
  "charging_state": 4,
  "current": -211,
  "temperature": 14,
  "bytes": 52
}
```

Six (6) of these are published via MQTT, and HA autodiscovers them - making configuration super easy. ( What it misses is the autodiscovery of the entity for the vacuum.

```
I had to add it in manual, in my `configuration.yaml` file.  This really should be automatic, though. 
#  PC-Wain's modified code autoconfigured everything except
#  the commands... using MQTT Explorer and the HASS interface
#  I tested commands and saw that it was receiving the published
#  packets for the commands... I just had to add the 3 lines below 
#  restart HA, and then look for MQTT Vacuum in the entities/devices

mqtt:
  vacuum:
    - command_topic: "vacuum/command"


```
Currently the lines that (attempt to) do all the configuration seem to be in the `connectMQTT()` function

```
void connectMQTT() 
{
  while (!mqttClient.connected()) 
  {
     // Attempt to connect
      if (mqttClient.connect(MQTT_CLIENT_NAME, MQTT_USER, MQTT_PASSWORD, MQTT_AVAILABILITY_TOPIC, 0, true, "offline")) 
      {
        debugV("MQTT connection successful, subscribing to command topic: %s", MQTT_COMMAND_TOPIC);
        mqttClient.subscribe(MQTT_COMMAND_TOPIC);
        mqttClient.publish(MQTT_AVAILABILITY_TOPIC, "online", true);
        publishHomeAssistantAutoDiscovery("", "", "", "", "", "vacuum", true);
        publishHomeAssistantAutoDiscovery("state", "State", "state", "", "", "sensor", false);
        publishHomeAssistantAutoDiscovery("battery", "Battery", "battery_level", "battery", "%", "sensor", false);
        publishHomeAssistantAutoDiscovery("voltage", "Voltage", "voltage / 1000", "battery", "V", "sensor", false);
        publishHomeAssistantAutoDiscovery("temperature", "Temperature", "temperature", "temperature", "°C", "sensor", false);
        publishHomeAssistantAutoDiscovery("dirt_level", "Dirt Level", "dirt_level / 255 * 100 | round(0)", "temperature", "%", "sensor", false);
      } 
      else 
      {
        delay(MQTT_RECONNECT_DELAY);
      }
  }
}

```

The line reading ` publishHomeAssistantAutoDiscovery("", "", "", "", "", "vacuum", true);` is, I believe where the change must take place.

I want to publish (advertise like in Bonjour) a vacuum that is MQTT...    [MQTT Vacuum Integration](https://www.home-assistant.io/integrations/vacuum.mqtt/) may have some hints, but doesn't seem to offer anything in terms of autoconfiguration.
